spring.application.name=erp-system

#Po??czenie do bazy danych
spring.datasource.url=jdbc:postgresql://localhost:5432/erp_db
spring.datasource.username=erp_user
spring.datasource.password=erp_password
spring.datasource.driver-class-name=org.postgresql.Driver

#Konfiguracja JPA / Hibernate (Twojego ORM)
# update = automatycznie twórz tabele w bazie na podstawie klas Java
spring.jpa.hibernate.ddl-auto=update
# show-sql = pokazuj zapytania SQL w konsoli
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# dialect = mówi Hibernate'owi, ?e gada z Postgresem
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect