spring.application.name=erp-system

spring.datasource.url=jdbc:postgresql://localhost:5432/erp_db
spring.datasource.username=erp_user
spring.datasource.password=erp_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
loggin.pattern.console={"timestamp":"%d{yyyy-MM-dd HH:mm:ss}","level":"%p","logger":"%c","message":"%m"}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.profiles.active=dev
app.security.pepper=SuperERP2026!@#

app.security.jwt.secret-key=TuWpiszBardzoDlugiLosowyCiagZnakowKtoryMaMinimum64ZnakiDlaBezpieczenstwa1234567890!
#Jeden dzień zycia tokena
app.security.jwt.expiration=86400000

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.prometheus.enabled=true
management.endpoint.health.show-details=always
management.endpoint.mappings.access=unrestricted


