### KROK 1: MAGAZYN - Dodaj produkt (Laptop)
POST http://localhost:8080/api/inventory/products
Content-Type: application/json

{
  "name": "Laptop Gamingowy PRO",
  "price": 5000.00,
  "skuCode": "DELL-G15-PRO",
  "stockQuantity": 10
}

### KROK 2: CRM - Dodaj Klienta (Jan Kowalski)
# To jest kluczowe! Musimy stworzyć klienta, żeby dostać jego ID (zazwyczaj 1).
POST http://localhost:8080/api/clients
Content-Type: application/json

{
  "firstName": "Jan",
  "lastName": "Kowalski",
  "email": "jan.kowalski@firma.pl",
  "phoneNumber": "123-456-789"
}

### KROK 3: SPRZEDAŻ - Jan Kowalski kupuje Laptopa
# Zwróć uwagę na pole "clientId": 1. Bez tego zamówienie nie przejdzie.
POST http://localhost:8080/api/sales/orders
Content-Type: application/json

{
  "clientId": 3,
  "items": [
    {
      "productId": 1,
      "quantity": 2
    }
  ]
}

### KROK 4: SPRZEDAŻ - Pobierz szczegóły zamówienia
# Sprawdź w odpowiedzi JSON, czy widzisz pola: "clientName": "Jan Kowalski" i "clientEmail".
# Jeśli tak -> SUKCES! Połączyliśmy moduły.
GET http://localhost:8080/api/sales/orders/1


### KROK 5: Pobieranie wszysktich zamówień danego klienta
GET http://localhost:8080/api/sales/orders/client/1

### KROK 6: Pobieranie danego klienta
GET http://localhost:8080/api/clients/99